#############################################################################
# Makefile for building: biblioteca_virtuale
# Generated by qmake (3.1) (Qt 6.2.4)
# Project:  Biblioteca_virtuale.pro
# Template: app
# Command: /usr/lib/qt6/bin/qmake -o Makefile Biblioteca_virtuale.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/lib/qt6/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt6/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt6/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = biblioteca_virtuale1.0.0
DISTDIR = /mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale/.tmp/biblioteca_virtuale1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		interfaccia_grafica/adminarea.cpp \
		interfaccia_grafica/librarymanager.cpp \
		interfaccia_grafica/visitorwidget.cpp \
		interfaccia_grafica/mainwindow.cpp \
		interfaccia_grafica/userarea.cpp \
		JSON/jsonmanager.cpp \
		modello_logico/biblioteca.cpp \
		modello_logico/cartaceo.cpp \
		modello_logico/cd.cpp \
		modello_logico/film.cpp \
		modello_logico/libri.cpp \
		modello_logico/manga.cpp \
		modello_logico/multimedia.cpp \
		modello_logico/riviste.cpp qrc_resources.cpp \
		moc_adminarea.cpp \
		moc_librarymanager.cpp \
		moc_mainwindow.cpp \
		moc_userarea.cpp \
		moc_jsonmanager.cpp
OBJECTS       = main.o \
		adminarea.o \
		librarymanager.o \
		visitorwidget.o \
		mainwindow.o \
		userarea.o \
		jsonmanager.o \
		biblioteca.o \
		cartaceo.o \
		cd.o \
		film.o \
		libri.o \
		manga.o \
		multimedia.o \
		riviste.o \
		qrc_resources.o \
		moc_adminarea.o \
		moc_librarymanager.o \
		moc_mainwindow.o \
		moc_userarea.o \
		moc_jsonmanager.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		Biblioteca_virtuale.pro interfaccia_grafica/adminarea.h \
		JSON/jsonobserver.h \
		interfaccia_grafica/librarymanager.h \
		interfaccia_grafica/visitor.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/mainwindow.h \
		interfaccia_grafica/userarea.h \
		JSON/jsonmanager.h \
		modello_logico/biblioteca.h \
		modello_logico/cartaceo.h \
		modello_logico/cd.h \
		modello_logico/film.h \
		modello_logico/libri.h \
		modello_logico/manga.h \
		modello_logico/multimedia.h \
		modello_logico/riviste.h main.cpp \
		interfaccia_grafica/adminarea.cpp \
		interfaccia_grafica/librarymanager.cpp \
		interfaccia_grafica/visitorwidget.cpp \
		interfaccia_grafica/mainwindow.cpp \
		interfaccia_grafica/userarea.cpp \
		JSON/jsonmanager.cpp \
		modello_logico/biblioteca.cpp \
		modello_logico/cartaceo.cpp \
		modello_logico/cd.cpp \
		modello_logico/film.cpp \
		modello_logico/libri.cpp \
		modello_logico/manga.cpp \
		modello_logico/multimedia.cpp \
		modello_logico/riviste.cpp
QMAKE_TARGET  = biblioteca_virtuale
DESTDIR       = 
TARGET        = biblioteca_virtuale


first: all
####### Build rules

biblioteca_virtuale:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Biblioteca_virtuale.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		Biblioteca_virtuale.pro \
		IMG/resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile Biblioteca_virtuale.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
Biblioteca_virtuale.pro:
IMG/resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Biblioteca_virtuale.pro

qmake_all: FORCE


all: Makefile biblioteca_virtuale

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents IMG/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents interfaccia_grafica/adminarea.h JSON/jsonobserver.h interfaccia_grafica/librarymanager.h interfaccia_grafica/visitor.h interfaccia_grafica/visitorwidget.h interfaccia_grafica/mainwindow.h interfaccia_grafica/userarea.h JSON/jsonmanager.h modello_logico/biblioteca.h modello_logico/cartaceo.h modello_logico/cd.h modello_logico/film.h modello_logico/libri.h modello_logico/manga.h modello_logico/multimedia.h modello_logico/riviste.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp interfaccia_grafica/adminarea.cpp interfaccia_grafica/librarymanager.cpp interfaccia_grafica/visitorwidget.cpp interfaccia_grafica/mainwindow.cpp interfaccia_grafica/userarea.cpp JSON/jsonmanager.cpp modello_logico/biblioteca.cpp modello_logico/cartaceo.cpp modello_logico/cd.cpp modello_logico/film.cpp modello_logico/libri.cpp modello_logico/manga.cpp modello_logico/multimedia.cpp modello_logico/riviste.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: IMG/resources.qrc \
		/usr/lib/qt6/libexec/rcc \
		IMG/e_finita_la_pace.png \
		IMG/focus.png \
		IMG/vinland_saga2.png \
		IMG/ace_ventura.png \
		IMG/resources.qrc \
		IMG/shrek.png \
		IMG/harry_potter.png \
		IMG/cook_inc.png \
		IMG/skyscraper.png \
		IMG/vinland_saga.png \
		IMG/isola_tesoro.png \
		IMG/biblioteca.png \
		IMG/bleach.png \
		IMG/via_pal2.png \
		IMG/via_pal.png \
		IMG/dark_side.png \
		IMG/vanity_fair.png \
		IMG/la_divina_commedia.png \
		IMG/vanity_fair2.png \
		IMG/la_divina_commedia2.png \
		IMG/onepiece.png \
		IMG/skyscraper2.png
	/usr/lib/qt6/libexec/rcc -name resources IMG/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_adminarea.cpp moc_librarymanager.cpp moc_mainwindow.cpp moc_userarea.cpp moc_jsonmanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_adminarea.cpp moc_librarymanager.cpp moc_mainwindow.cpp moc_userarea.cpp moc_jsonmanager.cpp
moc_adminarea.cpp: interfaccia_grafica/adminarea.h \
		interfaccia_grafica/mainwindow.h \
		JSON/jsonobserver.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include interfaccia_grafica/adminarea.h -o moc_adminarea.cpp

moc_librarymanager.cpp: interfaccia_grafica/librarymanager.h \
		modello_logico/riviste.h \
		modello_logico/cartaceo.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include interfaccia_grafica/librarymanager.h -o moc_librarymanager.cpp

moc_mainwindow.cpp: interfaccia_grafica/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include interfaccia_grafica/mainwindow.h -o moc_mainwindow.cpp

moc_userarea.cpp: interfaccia_grafica/userarea.h \
		interfaccia_grafica/mainwindow.h \
		JSON/jsonobserver.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		modello_logico/film.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/riviste.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include interfaccia_grafica/userarea.h -o moc_userarea.cpp

moc_jsonmanager.cpp: JSON/jsonmanager.h \
		interfaccia_grafica/adminarea.h \
		interfaccia_grafica/mainwindow.h \
		JSON/jsonobserver.h \
		interfaccia_grafica/userarea.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		modello_logico/film.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/riviste.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/mnt/c/Users/acer/Desktop/Progetto/biblioteca_virtuale/Biblioteca_virtuale -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include JSON/jsonmanager.h -o moc_jsonmanager.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp interfaccia_grafica/mainwindow.h \
		interfaccia_grafica/userarea.h \
		JSON/jsonobserver.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		modello_logico/film.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/riviste.h \
		interfaccia_grafica/adminarea.h \
		interfaccia_grafica/librarymanager.h \
		JSON/jsonmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

adminarea.o: interfaccia_grafica/adminarea.cpp interfaccia_grafica/adminarea.h \
		interfaccia_grafica/mainwindow.h \
		JSON/jsonobserver.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		JSON/jsonmanager.h \
		interfaccia_grafica/userarea.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		modello_logico/film.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/riviste.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminarea.o interfaccia_grafica/adminarea.cpp

librarymanager.o: interfaccia_grafica/librarymanager.cpp interfaccia_grafica/librarymanager.h \
		modello_logico/riviste.h \
		modello_logico/cartaceo.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/film.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o librarymanager.o interfaccia_grafica/librarymanager.cpp

visitorwidget.o: interfaccia_grafica/visitorwidget.cpp interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		modello_logico/film.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/riviste.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visitorwidget.o interfaccia_grafica/visitorwidget.cpp

mainwindow.o: interfaccia_grafica/mainwindow.cpp interfaccia_grafica/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o interfaccia_grafica/mainwindow.cpp

userarea.o: interfaccia_grafica/userarea.cpp interfaccia_grafica/userarea.h \
		interfaccia_grafica/mainwindow.h \
		JSON/jsonobserver.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		modello_logico/film.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/riviste.h \
		JSON/jsonmanager.h \
		interfaccia_grafica/adminarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userarea.o interfaccia_grafica/userarea.cpp

jsonmanager.o: JSON/jsonmanager.cpp JSON/jsonmanager.h \
		interfaccia_grafica/adminarea.h \
		interfaccia_grafica/mainwindow.h \
		JSON/jsonobserver.h \
		interfaccia_grafica/userarea.h \
		modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h \
		modello_logico/film.h \
		modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/riviste.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jsonmanager.o JSON/jsonmanager.cpp

biblioteca.o: modello_logico/biblioteca.cpp modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o biblioteca.o modello_logico/biblioteca.cpp

cartaceo.o: modello_logico/cartaceo.cpp modello_logico/cartaceo.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cartaceo.o modello_logico/cartaceo.cpp

cd.o: modello_logico/cd.cpp modello_logico/cd.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cd.o modello_logico/cd.cpp

film.o: modello_logico/film.cpp modello_logico/film.h \
		modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o film.o modello_logico/film.cpp

libri.o: modello_logico/libri.cpp modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libri.o modello_logico/libri.cpp

manga.o: modello_logico/manga.cpp modello_logico/manga.h \
		modello_logico/libri.h \
		modello_logico/cartaceo.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manga.o modello_logico/manga.cpp

multimedia.o: modello_logico/multimedia.cpp modello_logico/multimedia.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multimedia.o modello_logico/multimedia.cpp

riviste.o: modello_logico/riviste.cpp modello_logico/riviste.h \
		modello_logico/cartaceo.h \
		modello_logico/biblioteca.h \
		interfaccia_grafica/visitorwidget.h \
		interfaccia_grafica/visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o riviste.o modello_logico/riviste.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_adminarea.o: moc_adminarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminarea.o moc_adminarea.cpp

moc_librarymanager.o: moc_librarymanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_librarymanager.o moc_librarymanager.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_userarea.o: moc_userarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userarea.o moc_userarea.cpp

moc_jsonmanager.o: moc_jsonmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jsonmanager.o moc_jsonmanager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

